In [21]:
#Numpy stands for numerical python
#Collection of same type of Datatype and
#Homogenous
import numpy as np

In [6]:
#ndarray
x = np.array([1,2,3,4,5])
print(x)
print(type(x))
print(x.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int32


In [7]:
print(x.ndim) #number of dimensions
print(x.shape) #number of rows and columns
print(x.size) #len of ndarray
print(x.itemsize) #bytes allocated by

1
(5,)
5
4


In [11]:
y = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(y)
print(type(y))

[[1 2 3 4 5]
 [6 7 8 9 0]]
<class 'numpy.ndarray'>


In [14]:
print(y.dtype)
print(y.ndim)
print(x.shape)
print(x.size)
print(x.itemsize)

int32
2
(5,)
5
4


In [16]:
z = np.array([[1.1,2.2,3.3,4.4,5.5],[6.6,7.7,8.8,9.9,0.0]])
print(z)
print(type(z))

[[1.1 2.2 3.3 4.4 5.5]
 [6.6 7.7 8.8 9.9 0. ]]
<class 'numpy.ndarray'>


In [17]:
print(z.dtype)
print(z.ndim)
print(z.shape)
print(z.size)
print(z.itemsize)

float64
2
(2, 5)
10
8


In [19]:
w = np.array([[1],
              [2],
              [3]])
print(w)
print(type(w))
print(w.dtype)
print(w.ndim)
print(w.shape)
print(w.size)
print(w.itemsize)

[[1]
 [2]
 [3]]
<class 'numpy.ndarray'>
int32
2
(3, 1)
3
4


### Type Casting

In [22]:
a = np.zeros(4)
print(a)

[0. 0. 0. 0.]


In [23]:
b = np.zeros(4,dtype = int)
print(b)

[0 0 0 0]


In [24]:
c = np.ones(5)
print(c)

[1. 1. 1. 1. 1.]


In [25]:
d = np.ones(5,dtype = int)
print(d)

[1 1 1 1 1]


In [26]:
e = np.full((5,),7)
print(e)

[7 7 7 7 7]


In [27]:
f = np.full((3,2),9,dtype = float)
print(f)

[[9. 9.]
 [9. 9.]
 [9. 9.]]


In [28]:
g = np.zeros((2,2),dtype = int)
print(g)

[[0 0]
 [0 0]]


In [32]:
j = np.arange(1,11)
print(j)
print(type(j))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [33]:
k = np.arange(0,100,5)
print(k)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [34]:
l = np.arange(0,6.0,0.6)
print(l)

[0.  0.6 1.2 1.8 2.4 3.  3.6 4.2 4.8 5.4]


### Reshape

In [37]:
m = np.arange(1,17).reshape(8,2)
print(m)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]


In [38]:
#create an ndarray with 3x3
#value should start with 21
n = np.arange(21,30).reshape(3,3)
print(n)

[[21 22 23]
 [24 25 26]
 [27 28 29]]


In [40]:
q = np.arange(1,10).reshape(3,3)
print(q)
z = np.arange(11,20).reshape(3,3)
print(z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [41]:
sum = q+z
print(sum)

[[12 14 16]
 [18 20 22]
 [24 26 28]]


In [42]:
sub = q-z
print(sub)

[[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]


In [43]:
#Universal Function
c4 = np.array([1,2,3,4])
print(c4)
print(np.sqrt(c4))
print(np.log(c4))
print(np.sin(c4))

[1 2 3 4]
[1.         1.41421356 1.73205081 2.        ]
[0.         0.69314718 1.09861229 1.38629436]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [44]:
#aggregate function
d1 = np.array([3.3,4.6,7.8,2.1,1.0])
print(d1)
print(d1.sum())
print(d1.min())
print(d1.max())
print(d1.mean())
print(d1.std())

[3.3 4.6 7.8 2.1 1. ]
18.8
1.0
7.8
3.7600000000000002
2.3499787233079363


In [45]:
s1 = "Machine Learning"
print(s1)

Machine Learning


In [48]:
print(s1[1:8])
print(s1[:11])
print(s1[6:])
print(s1[:])

achine 
Machine Lea
e Learning
Machine Learning


In [50]:
#step/stride
s1 = "Machine Learning"
print(s1[::1]) #skip 0 char
print(s1[::2]) #skip 1 char
print(s1[::3]) #skip 2 char

Machine Learning
McieLann
Mheeng


In [51]:
print(s1[2:15:2])
print(s1[1:14:2])

cieLann
ahn eri
