### Pandas
##### Used for Preprocessing
##### Series - 1dimension,(Unique)
##### DataFrame - more than 1dimension
##### Numpy array can be converted to Pandas series, But Pandas series can not be converted to Numpy array

## Pandas Series

In [3]:
a = pd.Series([12,-4,7,9])
print(a)
print(type(a))
print(a.values)
print(a.index)

0    12
1    -4
2     7
3     9
dtype: int64
<class 'pandas.core.series.Series'>
[12 -4  7  9]
RangeIndex(start=0, stop=4, step=1)


In [4]:
#Creating series with user defines row-index
b = pd.Series([12,-4,7,9], index = ['a','b','c','d'])
print(b)
#Retrieving values and index
print(b.values)
print(b.index)

a    12
b    -4
c     7
d     9
dtype: int64
[12 -4  7  9]
Index(['a', 'b', 'c', 'd'], dtype='object')


In [13]:
print(b[2])
print(b['c'])
print(b[0:2])
print(b['a':'c'])

7
7
a    12
b    -4
dtype: int64
a    12
b    -4
c     7
dtype: int64


C:\Users\Aspir\AppData\Local\Temp\ipykernel_26824\2921248488.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(b[2])


In [16]:
print(b['b'])

-4


In [19]:
b[1] = 5
print(b[1])

5


C:\Users\Aspir\AppData\Local\Temp\ipykernel_26824\1452052274.py:1: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  b[1] = 5
C:\Users\Aspir\AppData\Local\Temp\ipykernel_26824\1452052274.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(b[1])


In [22]:
b[3]
print(b[3])

6


C:\Users\Aspir\AppData\Local\Temp\ipykernel_26824\3459437454.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  b[3]
C:\Users\Aspir\AppData\Local\Temp\ipykernel_26824\3459437454.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(b[3])


In [20]:
b[3] = 6
print(b[3])

6


C:\Users\Aspir\AppData\Local\Temp\ipykernel_26824\3803783470.py:1: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  b[3] = 6
C:\Users\Aspir\AppData\Local\Temp\ipykernel_26824\3803783470.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(b[3])


In [24]:
#Creating series from ndarray
import numpy as np
x = np.array([1,2,3,4])
print(x)

[1 2 3 4]


In [25]:
z = pd.Series(x)
print(z)

0    1
1    2
2    3
3    4
dtype: int32


In [26]:
print(x)

[1 2 3 4]


In [30]:
print(type(x))
print(type(z))

<class 'numpy.ndarray'>
<class 'pandas.core.series.Series'>


In [31]:
#filtreing values

In [33]:
a = pd.Series([12,-4,7,9])
print(a)

0    12
1    -4
2     7
3     9
dtype: int64


In [37]:
print(a>8)

0     True
1    False
2    False
3     True
dtype: bool


In [35]:
print(a[a>8])

0    12
3     9
dtype: int64


In [38]:
k = pd.Series([10,20,30,40,50])
print(k)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [41]:
print(k == 50)

0    False
1    False
2    False
3    False
4     True
dtype: bool


In [42]:
print(k[k == 50])

4    50
dtype: int64


In [43]:
print(k[k<50])

0    10
1    20
2    30
3    40
dtype: int64


In [45]:
print(k[k>40])

4    50
dtype: int64


In [50]:
#Evaluating values
g = pd.Series([1,0,2,1,2,3],
             index = ['white','white','blue','green',
                      'green','yellow'])
print(g)

white     1
white     0
blue      2
green     1
green     2
yellow    3
dtype: int64


In [58]:
#Used for preprocessing
print(g.unique())

[1 0 2 3]


In [60]:
#Used for preprocessing
print(g.value_counts()) #value repeating

1    2
2    2
0    1
3    1
Name: count, dtype: int64


In [61]:
#Used for preprocessing
print(g.isin([0,3]))

white     False
white      True
blue      False
green     False
green     False
yellow     True
dtype: bool


In [62]:
#Used for preprocessing
print(g[g.isin([0,3])])

white     0
yellow    3
dtype: int64


In [56]:
print(g['white'])

white    1
white    0
dtype: int64


In [66]:
#dropna()
data = pd.Series([1,np.NaN,3.5,np.NaN,7])
print(data)

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64


In [67]:
print(data.isnull())

0    False
1     True
2    False
3     True
4    False
dtype: bool


In [70]:
#Used for preprocessing
print(data[data.isnull()])

1   NaN
3   NaN
dtype: float64


In [71]:
#Used for preprocessing
print(data.isnull().sum())

2


In [72]:
print(data.notnull())

0     True
1    False
2     True
3    False
4     True
dtype: bool


In [73]:
print(data[data.notnull()])

0    1.0
2    3.5
4    7.0
dtype: float64


In [74]:
print(data.notnull().sum())

3


### Droping the null value

In [75]:
data = pd.Series([1,np.NaN,3.5,np.NaN,7])
print(data)

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64


In [77]:
data2 = data.dropna()
print(data2)

0    1.0
2    3.5
4    7.0
dtype: float64


In [78]:
print(data)

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64


In [79]:
#inplace is used change anything from the original dataset
data.dropna(inplace = True)
print(data)

0    1.0
2    3.5
4    7.0
dtype: float64


### Fillna

In [81]:
data = pd.Series([1,np.NaN,3.5,np.NaN,7])
print(data)

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64


In [82]:
data3 = data.fillna(0)
print(data3)

0    1.0
1    0.0
2    3.5
3    0.0
4    7.0
dtype: float64


In [83]:
print(data)

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64


In [84]:
data.fillna(3,inplace = True)
print(data)

0    1.0
1    3.0
2    3.5
3    3.0
4    7.0
dtype: float64


In [86]:
#Excersise
ll = pd.Series([50,np.NaN,70,80,np.NaN])
print(ll)

0    50.0
1     NaN
2    70.0
3    80.0
4     NaN
dtype: float64


In [87]:
print(type(ll))

<class 'pandas.core.series.Series'>


In [88]:
print(ll.values)

[50. nan 70. 80. nan]


In [89]:
print(ll.index)

RangeIndex(start=0, stop=5, step=1)


In [92]:
ll[2] = 60
print(ll)

0    50.0
1     NaN
2    60.0
3    70.0
4     NaN
dtype: float64


In [93]:
ll[3] = 70
print(ll)

0    50.0
1     NaN
2    60.0
3    70.0
4     NaN
dtype: float64


In [94]:
print(ll.unique())

[50. nan 60. 70.]


In [95]:
print(ll.value_counts())

50.0    1
60.0    1
70.0    1
Name: count, dtype: int64


In [96]:
print(ll[ll.isin([0,60])])

2    60.0
dtype: float64


In [97]:
print(ll[ll.isnull()])

1   NaN
4   NaN
dtype: float64


In [98]:
print(ll.isnull().sum())

2


In [100]:
ll.fillna(20,inplace = True)
print(ll)

0    50.0
1    20.0
2    60.0
3    70.0
4    20.0
dtype: float64


In [101]:
ll.dropna(inplace = True)
print(ll)

0    50.0
1    20.0
2    60.0
3    70.0
4    20.0
dtype: float64
